//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake_Shop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_IMAGES
    {
        public int ImageID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ImagePath { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
